CREATE TABLE ErrorCodes
(
	Code INT PRIMARY KEY,
	TextIn NVARCHAR(255) NOT NULL
);

CREATE TABLE Categories
(
	Id INT PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	Parent INT NOT NULL,
	Image NVARCHAR(255) NOT NULL
);